# serverless.yml
service: imagegram

provider:
  name: aws
  runtime: nodejs14.18.0
  stage: dev
  profile: default
  region: us-east-1
  memorySize: 512

functions:
  app:
    handler: index.handler
    events:
      - http:
          path: account
          method: get
      - http:
          path: account/{id}
          method: get
      - http:
          path: createaccount
          method: post
      - http:
          path: account/{id}
          method: put
      - http:
          path: account/{id}
          method: delete

plugins:
  - serverless-offline