# serverless.yml
service: imagegram
package:
  individually: true

provider:
  name: aws
  runtime: nodejs10.x
  memorySize: 128
  timeout: 10
  stage: production
  region: us-east-1

functions:
  app:
    handler: index.handler
    events:
      - http:
          path: createcreator
          method: post
      - http:
          path: createpost
          method: post
      - http:
          path: createcomment
          method: post
      - http:
          path: getallpost
          method: get
      - http:
          path: deletecreator
          method: delete

plugins:
  - serverless-offline
  