# serverless.yml
service: imagegram
package:
  individually: true

custom:
  cors:
    origin: '*'
    headers:
      - Cache-Control
      - Content-Type
      - Authorization
      - Accept
      - Accept-Encoding
      - X-Amz-Date
      - X-Api-Key
      - X-Amz-Security-Token
      - X-Amz-User-Agent
      - x-account-id
    allowCredentials: false

provider:
  name: aws
  runtime: nodejs10.x
  memorySize: 128
  timeout: 10
  stage: production
  region: us-east-1

functions:
  app:
    handler: index.handler
    events:
      - http:
          path: createcreator
          method: post
      - http:
          path: createpost
          method: post
      - http:
          path: createpost2
          method: post
      - http:
          path: addcomment
          method: post
      - http:
          path: getallpost
          method: get
      - http:
          path: deletecreator
          method: delete

plugins:
  - serverless-offline
  